In [1]:
import pandas as pd

# 1. Getting & Knowing Data

##### 1. 데이터를 로드하라. 데이터는 \t을 기준으로 구분되어있다.  
DataUrl = https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv", sep = "\t")

##### 2. 데이터의 상위 5개 행을 출력하라

In [3]:
print(df.head())

       gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0  3326086514  1504279457970          1949         9       1           2
1  3229566029  1497848803862          1851         9       1           1
2  3327363504  1504360103310          1493         9       1           2
3  3326856598  1504348503996          1758         9       1           1
4  3330080762  1504554410899          2094         9       1           2

   firstTower  firstInhibitor  firstBaron  firstDragon  ...  t2_towerKills  \
0           1               1           1            1  ...              5
1           1               1           0            1  ...              2
2           1               1           1            2  ...              2
3           1               1           1            1  ...              0
4           1               1           1            1  ...              3

   t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
0                  0              0               1                   1
1                  0              0               0                   0
2                  0              0               1                   0
3                  0              0               0                   0
4                  0              0               1                   0

   t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5
0      114       67       43       16       51
1       11       67      238       51      420
2      157      238      121       57       28
3      164       18      141       40       51
4       86       11      201      122       18

[5 rows x 61 columns]

##### 3. 데이터의 행과 열의 갯수를 파악하라

In [4]:
print(df.shape)

(51490, 61)

##### 4. 전체 컬럼을 출력하라

In [5]:
print(df.columns)

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

##### 5. 6번째 컬럼명을 출력하라

In [6]:
print(df.columns[5])

firstBlood

##### 6. 6번째 컬럼의 데이터 타입을 확인하라

In [7]:
print(df.iloc[:,5].dtype)

int64

##### 7. 데이터의 인덱스 구성은 어떤가

In [8]:
print(df.index)

RangeIndex(start=0, stop=51490, step=1)

##### 8. 6번째 컬럼의 3번째 값은 무엇인가?

In [9]:
print(df.iloc[2,5])

2

##### 9. 데이터를 로드하라. 컬럼이 한글이기에 적절한 처리해줘야함
DataUrl = https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv

In [10]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv", encoding = "euc-kr")
df

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.50
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.50
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.40
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.40
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

##### 10. 데이터 마지막 3개 행을 출력하라

In [11]:
print(df.tail(3))

         id          일자   시도명 읍면동명         거주인구       근무인구        방문인구  \
9618  32066  2020-04-30   제주시  도두동    28397.481   3144.895   84052.697
9619  32067  2020-04-30  서귀포시  안덕면   348037.846  29106.286  251129.660
9620  32068  2020-04-30   제주시   연동  1010643.372  65673.477  447622.068

           총 유동인구   평균 속도  평균 소요 시간  평균 기온  일강수량  평균 풍속
9618   115595.073  41.053    29.421   20.3   0.0    3.0
9619   628273.792  46.595    49.189   17.6   0.0    3.5
9620  1523938.917  40.863    27.765   14.1   0.0    4.8

##### 11. 수치형 변수를 가진 컬럼을 출력하라

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB
None

In [13]:
print(df.select_dtypes(exclude = "object").columns)

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

##### 12. 범주형 변수를 가진 컬럼을 출력하라

In [14]:
print(df.select_dtypes(include = "object").columns)

Index(['일자', '시도명', '읍면동명'], dtype='object')

##### 13. 각 컬럼의 결측치 숫자를 파악하라

In [15]:
print(df.isnull().sum())

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

##### 14. 각 컬럼의 데이터 수, 데이터 타입을 한 번에 확인하라

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

##### 15. 각 수치형 변수의 분포(사분위, 평균, 표준편차, 최대 , 최소)를 확인하라

In [17]:
print(df.select_dtypes(exclude = "object").describe())

                 id          거주인구           근무인구           방문인구        총 유동인구  \
count   9621.000000  9.621000e+03    9621.000000    9621.000000  9.621000e+03
mean   27258.000000  3.174315e+05   35471.201510  195889.561802  5.487922e+05
std     2777.487804  2.982079e+05   40381.214775  140706.090325  4.608802e+05
min    22448.000000  9.305552e+03    1407.936000   11538.322000  2.225181e+04
25%    24853.000000  9.539939e+04   12074.498000   99632.153000  2.216910e+05
50%    27258.000000  2.221105e+05   21960.928000  152805.335000  3.866935e+05
75%    29663.000000  4.106671e+05   40192.032000  236325.109000  6.406918e+05
max    32068.000000  1.364504e+06  263476.965000  723459.209000  2.066484e+06

             평균 속도     평균 소요 시간        평균 기온         일강수량        평균 풍속
count  9621.000000  9621.000000  9621.000000  9621.000000  9621.000000
mean     41.109084    37.215873    13.550828     6.972426     2.753171
std       8.758631    12.993786     7.745515    27.617260     1.498538
min      24.333000    12.667000    -9.600000     0.000000     0.000000
25%      34.250000    27.889000     7.600000     0.000000     1.700000
50%      39.640000    34.500000    13.400000     0.000000     2.400000
75%      49.105000    46.176000    19.700000     1.500000     3.400000
max     103.000000   172.200000    30.400000   587.500000    13.333000

##### 16. 거주인구 컬럼의 값들을 출력하라

In [18]:
print(df["거주인구"])

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

##### 17. 평균 속도 컬럼의 4분위 범위(IQR) 값을 구하여라

In [19]:
print(df["평균 속도"].quantile(0.75) - df["평균 속도"].quantile(0.25))

14.854999999999997

##### 18. 읍면동명 컬럼의 유일값 갯수를 출력하라

In [20]:
print(len(df["읍면동명"].unique()))

41

##### 19. 읍면동명 컬럼의 유일값을 모두 출력하라

In [21]:
print(df["읍면동명"].unique())

['도두동' '외도동' '이도2동' '일도1동' '대천동' '서홍동' '한경면' '송산동' '조천읍' '일도2동' '영천동'
 '예래동' '대륜동' '삼도1동' '이호동' '건입동' '중앙동' '삼양동' '삼도2동' '이도1동' '남원읍' '대정읍'
 '정방동' '효돈동' '아라동' '한림읍' '구좌읍' '용담1동' '오라동' '화북동' '연동' '표선면' '중문동' '성산읍'
 '안덕면' '천지동' '노형동' '동홍동' '용담2동' '봉개동' '애월읍']

# 2. Filtering & Sorting

##### 20. 데이터를 로드하라.
DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv’

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv")

##### 21. quantity컬럼 값이 3인 데이터를 추출하여 첫 5행을 출력하라

In [23]:
df[df["quantity"] == 3].iloc[:5]

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

##### 22. quantity컬럼 값이 3인 데이터를 추출하여 index를 0부터 정렬하고 첫 5행을 출력하라

In [24]:
df[df["quantity"] == 3].reset_index(drop = True).iloc[:5]

,order_id,quantity,item_name,choice_description,item_price
0,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,338,3,Bottled Water,NaN,$3.27
4,350,3,Canned Soft Drink,[Sprite],$3.75

##### 23. quantity , item_price 두개의 컬럼으로 구성된 새로운 데이터 프레임을 정의하라

In [25]:
target = df[["quantity", "item_price"]]
print(target)

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

##### 24. item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라

In [26]:
df["new_price"] = df["item_price"].str.replace("$", "").astype("float")
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

##### 25. new_price 컬럼이 5이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수를 구하여라

In [27]:
len(df[df["new_price"] <= 5])

1652

##### 26. item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화 하여라

In [28]:
df[df["item_name"] == "Chicken Salad Bowl"].reset_index(drop = True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...
105,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

##### 27. new_price값이 9 이하이고 item_name 값이 Chicken Salad Bowl 인 데이터 프레임을 추출하라

In [29]:
df[(df["new_price"] <= 9) & (df["item_name"] == "Chicken Salad Bowl")]

,order_id,quantity,item_name,choice_description,item_price,new_price
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
526,220,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
528,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
529,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
568,234,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
585,240,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
693,286,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Sour Cream, Cheese, Lett...",$8.75,8.75
702,289,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$8.75,8.75
762,314,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
1109,458,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1460,592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
1471,598,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1483,602,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
1547,628,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1601,649,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1621,654,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1756,709,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
1977,798,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
2031,818,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
2113,850,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",$8.75,8.75
2224,896,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...",$8.75,8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",$8.75,8.75
2728,1083,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
2858,1136,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
2883,1145,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
2897,1152,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, Cheese]",$8.75,8.75
2989,1189,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
3033,1206,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3069,1222,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$8.75,8.75
3117,1243,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3259,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
3261,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3310,1327,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
3315,1329,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",$8.75,8.75
3381,1357,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3411,1368,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Lettuce]]",$8.75,8.75
3623,1450,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3656,1461,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
3706,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Chees...",$8.75,8.75
3712,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
3790,1517,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
3798,1521,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3974,1592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Lettu...",$8.75,8.75
3997,1601,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
4012,1606,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
4035,1615,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
4064,1627,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4205,1679,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
4207,1679,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75
4333,1730,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese]]",$8.75,8.75
4352,1738,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75,8.75
4439,1769,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4520,1797,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

##### 28. df의 new_price 컬럼 값에 따라 오름차순으로 정리하고 index를 초기화 하여라

In [30]:
df.sort_values("new_price", ascending = True).reset_index(drop = True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,14,1,Canned Soda,[Dr. Pepper],$1.09,1.09
1,567,1,Canned Soda,[Coca Cola],$1.09,1.09
2,1518,1,Canned Soda,[Diet Coke],$1.09,1.09
3,1494,1,Canned Soda,[Sprite],$1.09,1.09
4,1093,1,Bottled Water,NaN,$1.09,1.09
...,...,...,...,...,...,...
4617,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
4618,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4619,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4620,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
4621,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

##### 29. df의 item_name 컬럼 값중 Chips 포함하는 경우의 데이터를 출력하라

In [31]:
df[df["item_name"].str.contains("Chips")]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

##### 30. df의 짝수번째 컬럼만을 포함하는 데이터프레임을 출력하라

In [32]:
df.iloc[:, ::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

##### 31. df의 new_price 컬럼 값에 따라 내림차순으로 정리하고 index를 초기화 하여라

In [33]:
df.sort_values("new_price", ascending = False).reset_index(drop = True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
1,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
2,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
3,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
4617,1396,1,Canned Soda,[Coca Cola],$1.09,1.09
4618,1396,1,Canned Soda,[Dr. Pepper],$1.09,1.09
4619,1405,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4620,424,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4621,24,1,Canned Soda,[Sprite],$1.09,1.09

##### 32. df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 인덱싱하라

In [34]:
df[df["item_name"].isin(["Steak Salad", "Bowl"])]

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

##### 33. df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라

In [35]:
target = df[df["item_name"].isin(["Steak Salad", "Bowl"])]
target.drop_duplicates("item_name", keep = "first")

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99

##### 34. df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 마지막 케이스만 남겨라

In [36]:
target = df[df["item_name"].isin(["Steak Salad", "Bowl"])]
target.drop_duplicates("item_name", keep = "last")

,order_id,quantity,item_name,choice_description,item_price,new_price
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

##### 35. df의 데이터 중 new_price값이 new_price값의 평균값 이상을 가지는 데이터들을 인덱싱하라

In [37]:
df[df["new_price"] >= df["new_price"].mean()]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

##### 36. df의 데이터 중 item_name의 값이 Izze 데이터를 Fizzy Lizzy로 수정하라(틀림)

In [38]:
df["item_name"] = df["item_name"].replace("Izze", "Fizzy Lizzy")

##### 37. df의 데이터 중 choice_description 값이 NaN 인 데이터의 갯수를 구하여라

In [39]:
print(df["choice_description"].isnull().sum())

1246

##### 38. ❌ df의 데이터 중 choice_description 값이 NaN 인 데이터를 NoData 값으로 대체하라(loc 이용)

In [40]:
df.loc[df.choice_description.isnull(), "choice_description"] = "NoData"

##### 39. df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라

In [41]:
df[df["choice_description"].str.contains("Black")]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

##### 40. df의 데이터 중 choice_description 값에 Vegetables 들어가지 않는 경우의 갯수를 출력하라

In [42]:
df[~df["choice_description"].str.contains("Vegetables")]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4614,1831,1,Bottled Water,NoData,$1.50,1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75

##### 41. df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라

In [43]:
df[df["item_name"].str.startswith("N")]

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

##### 42. df의 데이터 중 item_name 값의 단어갯수가 15개 이상인 데이터를 인덱싱하라(틀림)

In [44]:
df[df["item_name"].str.len() >= 15]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

##### 43. df의 데이터 중 new_price값이 lst에 해당하는 경우의 데이터 프레임을 구하고 그 갯수를 출력하라(틀림)
lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

In [45]:
lst = [1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
target = df[df["new_price"].isin(lst)]
display(target)
print(len(target))

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75

1393

# 3. Grouping

##### 44. 데이터를 로드하고 상위 5개 컬럼을 출력하라
DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv’

In [46]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

##### 45. 데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라(틀림)

In [47]:
df.value_counts("host_name").sort_values(ascending = False).head(5).reset_index(name = "count")

      host_name  count
0       Michael    417
1         David    403
2  Sonder (NYC)    327
3          John    294
4          Alex    279

##### 46. 데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라

In [48]:
df.value_counts("host_name").sort_values(ascending = False).reset_index(name = "counts")

          host_name  counts
0           Michael     417
1             David     403
2      Sonder (NYC)     327
3              John     294
4              Alex     279
...             ...     ...
11447       Ziporah       1
11448         A & H       1
11449          Ziva       1
11450            韦达       1
11451            馨惠       1

[11452 rows x 2 columns]

##### 47. neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

In [49]:
df.groupby(["neighbourhood_group", "neighbourhood"]).size().reset_index(name = "count")

    neighbourhood_group  neighbourhood  count
0                 Bronx       Allerton     42
1                 Bronx     Baychester      7
2                 Bronx        Belmont     24
3                 Bronx      Bronxdale     19
4                 Bronx    Castle Hill      9
..                  ...            ...    ...
216       Staten Island    Tottenville      7
217       Staten Island  West Brighton     18
218       Staten Island    Westerleigh      2
219       Staten Island    Willowbrook      1
220       Staten Island        Woodrow      1

[221 rows x 3 columns]

##### 48. ❌ neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

In [50]:
df.groupby(["neighbourhood_group", "neighbourhood"], as_index= False).size().groupby(['neighbourhood_group'], as_index=False).max()

  neighbourhood_group    neighbourhood  size
0               Bronx         Woodlawn    70
1            Brooklyn  Windsor Terrace  3920
2           Manhattan     West Village  2658
3              Queens         Woodside   900
4       Staten Island          Woodrow    48

##### 49. neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라

In [51]:
df.groupby("neighbourhood_group", as_index = False)["price"].describe()

,neighbourhood_group,count,mean,std,min,25%,50%,75%,max
0,Bronx,1091.0,87.496792,106.709349,0.0,45.0,65.0,99.0,2500.0
1,Brooklyn,20104.0,124.383207,186.873538,0.0,60.0,90.0,150.0,10000.0
2,Manhattan,21661.0,196.875814,291.383183,0.0,95.0,150.0,220.0,10000.0
3,Queens,5666.0,99.517649,167.102155,10.0,50.0,75.0,110.0,10000.0
4,Staten Island,373.0,114.812332,277.620403,13.0,50.0,75.0,110.0,5000.0

##### 50. neighbourhood_group 값에 따른 reviews_per_month 평균, 분산, 최대, 최소 값을 구하여라

In [52]:
df.groupby("neighbourhood_group", as_index = False)["reviews_per_month"].describe()

,neighbourhood_group,count,mean,std,min,25%,50%,75%,max
0,Bronx,876.0,1.837831,1.673284,0.02,0.4800,1.38,2.790,10.34
1,Brooklyn,16447.0,1.283212,1.516259,0.01,0.1800,0.66,1.980,14.00
2,Manhattan,16632.0,1.272131,1.628252,0.01,0.1700,0.61,1.890,58.50
3,Queens,4574.0,1.941200,2.213108,0.01,0.3700,1.21,2.790,20.94
4,Staten Island,314.0,1.872580,1.685495,0.02,0.7025,1.41,2.615,10.12

##### 51. neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

In [53]:
df.groupby(["neighbourhood", "neighbourhood_group"])["price"].mean()

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

##### 52. neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

In [54]:
df.groupby(['neighbourhood', 'neighbourhood_group'], as_index=False)['price'].mean()

       neighbourhood neighbourhood_group       price
0           Allerton               Bronx   87.595238
1      Arden Heights       Staten Island   67.250000
2           Arrochar       Staten Island  115.000000
3            Arverne              Queens  171.779221
4            Astoria              Queens  117.187778
..               ...                 ...         ...
216  Windsor Terrace            Brooklyn  138.993631
217        Woodhaven              Queens   67.170455
218         Woodlawn               Bronx   60.090909
219          Woodrow       Staten Island  700.000000
220         Woodside              Queens   85.097872

[221 rows x 3 columns]

##### 53. neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

In [55]:
target = df.groupby(['neighbourhood', 'neighbourhood_group'], as_index=False)['price'].mean()
target.fillna(-999)

       neighbourhood neighbourhood_group       price
0           Allerton               Bronx   87.595238
1      Arden Heights       Staten Island   67.250000
2           Arrochar       Staten Island  115.000000
3            Arverne              Queens  171.779221
4            Astoria              Queens  117.187778
..               ...                 ...         ...
216  Windsor Terrace            Brooklyn  138.993631
217        Woodhaven              Queens   67.170455
218         Woodlawn               Bronx   60.090909
219          Woodrow       Staten Island  700.000000
220         Woodside              Queens   85.097872

[221 rows x 3 columns]

##### 54. 데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라

In [56]:
df[df["neighbourhood_group"] == "Queens"].groupby("neighbourhood")["price"].describe()

,count,mean,std,min,25%,50%,75%,max
neighbourhood,,,,,,,,
Arverne,77.0,171.779221,193.347902,35.0,75.00,125.0,200.00,1500.0
Astoria,900.0,117.187778,349.898287,25.0,60.00,85.0,120.00,10000.0
Bay Terrace,6.0,142.000000,82.561492,32.0,92.25,141.5,187.75,258.0
Bayside,39.0,157.948718,407.561616,30.0,48.50,65.0,117.50,2600.0
Bayswater,17.0,87.470588,48.279289,45.0,55.00,70.0,105.00,230.0
Belle Harbor,8.0,171.500000,90.700449,85.0,103.00,155.0,206.25,350.0
Bellerose,14.0,99.357143,55.614894,42.0,61.25,85.0,103.75,240.0
Breezy Point,3.0,213.333333,31.754265,195.0,195.00,195.0,222.50,250.0
Briarwood,56.0,105.875000,136.026343,30.0,55.75,71.5,99.25,1000.0
Cambria Heights,26.0,81.730769,54.411438,31.0,50.00,60.0,95.00,250.0
College Point,19.0,88.000000,80.284217,44.0,54.00,60.0,83.50,400.0
Corona,64.0,59.171875,49.300682,23.0,35.75,40.0,69.25,359.0
Ditmars Steinway,309.0,95.029126,64.916198,22.0,55.00,79.0,107.00,600.0
Douglaston,8.0,82.750000,48.446583,40.0,45.00,65.0,105.50,178.0
East Elmhurst,185.0,81.183784,66.102101,16.0,45.00,60.0,99.00,700.0
Edgemere,11.0,94.727273,64.957049,40.0,46.50,65.0,139.50,200.0
Elmhurst,237.0,80.459916,62.422456,15.0,42.00,59.0,90.00,443.0
Far Rockaway,29.0,165.862069,229.294527,35.0,40.00,63.0,147.00,900.0
Flushing,426.0,93.514085,111.432390,15.0,50.00,65.0,98.00,1500.0
Forest Hills,144.0,121.625000,211.029308,16.0,59.00,80.0,116.00,2350.0
Fresh Meadows,32.0,99.500000,79.965315,39.0,55.00,72.0,96.25,375.0
Glendale,54.0,90.796296,56.840850,25.0,46.00,84.0,122.50,299.0
Hollis,14.0,88.642857,38.509953,50.0,57.50,77.5,100.00,175.0
Holliswood,4.0,135.750000,71.355331,79.0,94.75,112.5,153.50,239.0
Howard Beach,20.0,115.400000,65.130153,40.0,61.00,100.0,153.75,250.0
Jackson Heights,186.0,80.897849,46.373167,23.0,49.25,68.5,100.00,260.0
Jamaica,231.0,95.770563,89.816742,10.0,50.00,70.0,125.00,1000.0
Jamaica Estates,19.0,182.947368,170.311634,35.0,66.50,135.0,250.00,750.0
Jamaica Hills,8.0,132.125000,106.323546,50.0,65.00,83.5,151.25,325.0
Kew Gardens,32.0,88.375000,51.306008,35.0,53.75,67.5,100.00,219.0
Kew Gardens Hills,26.0,112.307692,78.934286,40.0,53.75,92.5,146.50,399.0
Laurelton,18.0,95.333333,65.996435,34.0,42.75,75.0,121.25,254.0
Little Neck,5.0,75.200000,48.669292,32.0,45.00,50.0,100.00,149.0
Long Island City,537.0,127.465549,124.617427,30.0,70.00,99.0,150.00,2000.0
Maspeth,110.0,83.645455,47.155139,11.0,50.00,65.0,100.00,245.0
Middle Village,31.0,109.580645,59.473677,28.0,70.00,99.0,119.50,265.0
Neponsit,3.0,274.666667,75.002222,200.0,237.00,274.0,312.00,350.0
Ozone Park,62.0,85.274194,41.296675,25.0,58.50,75.0,107.50,200.0
Queens Village,60.0,83.933333,48.851510,25.0,50.00,75.0,99.25,320.0
Rego Park,106.0,83.877358,60.489700,21.0,47.25,67.0,98.00,300.0
Richmond Hill,94.0,87.117021,58.941899,28.0,50.00,65.0,100.00,300.0
Ridgewood,423.0,77.184397,51.276816,20.0,45.00,60.0,90.00,375.0
Rockaway Beach,56.0,132.178571,79.086169,49.0,85.75,125.0,150.00,545.0
Rosedale,59.0,76.694915,54.442077,22.0,52.50,65.0,80.00,350.0
South Ozone Park,40.0,82.400000,67.970506,29.0,49.50,69.0,86.00,400.0
Springfield Gardens,85.0,94.235294,49.908403,40.0,60.00,80.0,101.00,300.0
St. Albans,76.0,100.828947,97.416137,25.0,50.00,61.5,101.25,600.0
Sunnyside,363.0,84.865014,52.227837,12.0,50.00,75.0,100.00,600.0
Whitestone,11.0,107.545455,116.756468,35.0,39.50,49.0,112.50,400.0
Woodhaven,88.0,67.170455,40.527335,10.0,45.00,52.0,70.25,250.0
Woodside,235.0,85.097872,70.724116,28.0,44.50,60.0,100.00,500.0

##### 55. 데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라

In [57]:
df.groupby(['neighbourhood_group', 'room_type']).size() / df.groupby('neighbourhood_group').size()

neighbourhood_group  room_type
Bronx                Entire home/apt    0.347388
                     Private room       0.597617
                     Shared room        0.054995
Brooklyn             Entire home/apt    0.475478
                     Private room       0.503979
                     Shared room        0.020543
Manhattan            Entire home/apt    0.609344
                     Private room       0.368496
                     Shared room        0.022160
Queens               Entire home/apt    0.369926
                     Private room       0.595129
                     Shared room        0.034945
Staten Island        Entire home/apt    0.471850
                     Private room       0.504021
                     Shared room        0.024129
dtype: float64

# 4. Apply , Map
카드 이용 데이터 : https://www.kaggle.com/sakshigoyal7/credit-card-customers  
DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv’

##### 56. 데이터를 로드하고 데이터 행과 열의 갯수를 출력하라

In [58]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv")
df.shape

(10127, 19)

##### 57. Income_Category의 카테고리를 map 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라
Unknown : N  
Less than $40K : a  
$40K - $60K : b  
$60K - $80K : c  
$80K - $120K : d  
$120K +’ : e

In [59]:
def category(x):
    if x == "Unknown": return "N"
    elif x == "Less than $40K" : return "a"
    elif x == "$40K - $60K" : return "b"
    elif x == "$60K - $80K" : return "c"
    elif x == "$80K - $120K" : return "d"
    elif x == "$120K +" : return "e"

df["newIncome"] = df["Income_Category"].map(category)
df

# income_map = {
#     "Unknown" : "N",
#     "Less than $40K": "a",
#     "$40K - $60K": "b",
#     "$60K - $80K": "c",
#     "$80K - $120K": "d",
#     "$120K +": "e"
# }
# 
# df["newIncome"] = df["Income_Category"].map(income_map)

,Unnamed: 0,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,newIncome
0,0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,c
1,1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,a
2,2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,d
3,3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,a
4,4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,b
10123,10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,b
10124,10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,a
10125,10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,b
10126,10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,a

##### 58. Income_Category의 카테고리를 apply 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라 
Unknown : N
Less than $40K : a  
$40K - $60K : b  
$60K - $80K : c  
$80K - $120K : d  
$120K +’ : e

In [60]:
def category(x):
    if x == "Unknown": return "N"
    elif x == "Less than $40K" : return "a"
    elif x == "$40K - $60K" : return "b"
    elif x == "$60K - $80K" : return "c"
    elif x == "$80K - $120K" : return "d"
    elif x == "$120K +" : return "e"

df["newIncome"] = df["Income_Category"].apply(category)

##### 59. Customer_Age의 값을 이용하여 나이 구간을 AgeState 컬럼으로 정의하라. (0~9 : 0 , 10~19 :10 , 20~29 :20 … 각 구간의 빈도수를 출력하라

In [61]:
df["AgeState"] = df["Customer_Age"].apply(lambda x: x // 10 * 10)
df

,Unnamed: 0,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,...,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,newIncome,AgeState
0,0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,...,5,1,3,12691.0,777,11914.0,1.335,1144,c,40
1,1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,...,6,1,2,8256.0,864,7392.0,1.541,1291,a,40
2,2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,...,4,1,0,3418.0,0,3418.0,2.594,1887,d,50
3,3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,...,3,4,1,3313.0,2517,796.0,1.405,1171,a,40
4,4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,...,5,1,0,4716.0,0,4716.0,2.175,816,c,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,...,3,2,3,4003.0,1851,2152.0,0.703,15476,b,50
10123,10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,...,4,2,3,4277.0,2186,2091.0,0.804,8764,b,40
10124,10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,...,5,3,4,5409.0,0,5409.0,0.819,10291,a,40
10125,10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,...,4,3,3,5281.0,0,5281.0,0.535,8395,b,30
10126,10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,...,6,2,4,10388.0,1961,8427.0,0.703,10294,a,40

##### 60. Education_Level의 값중 Graduate단어가 포함되는 값은 1 그렇지 않은 경우에는 0으로 변경하여 newEduLevel 컬럼을 정의하고 빈도수를 출력하라

In [62]:
df["newEduLevel"] = df["Education_Level"].map(lambda x: 1 if "Graduate" in x else 0)
df["newEduLevel"].value_counts()

newEduLevel
0    6483
1    3644
Name: count, dtype: int64

##### 61. Credit_Limit 컬럼값이 4500 이상인 경우 1 그외의 경우에는 모두 0으로 하는 newLimit 정의하라. newLimit 각 값들의 빈도수를 출력하라

In [63]:
df["newLimit"] = df["Credit_Limit"].apply(lambda x : 1 if x >= 4500 else 0)
df.value_counts("newLimit")

newLimit
1    5096
0    5031
Name: count, dtype: int64

##### 62. ❌ Marital_Status 컬럼값이 Married 이고 Card_Category 컬럼의 값이 Platinum인 경우 1 그외의 경우에는 모두 0으로 하는 newState컬럼을 정의하라. newState의 각 값들의 빈도수를 출력하라

In [64]:
def check(x):
    if x["Marital_Status"] == "Married" and x["Card_Category"] == "Platinum": return 1
    else: return 0

df["newState"] = df.apply(check, axis = 1) # axis = 1 : 행 단위 으로 함수 적용 => 각 행을 Series로 전달해 함수 실행
df["newState"].value_counts()

newState
0    10120
1        7
Name: count, dtype: int64

##### 63. Gender 컬럼값 M인 경우 male F인 경우 female로 값을 변경하여 Gender 컬럼에 새롭게 정의하라. 각 value의 빈도를 출력하라

In [65]:
df["Gender"] = df["Gender"].apply(lambda x: "male" if x == "M" else "female")

# 5. Time Series
주가 데이터 : https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data  
DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv’

##### 64. 데이터를 로드하고 각 열의 데이터 타입을 파악하라

In [66]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   object
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB

##### 65. Yr_Mo_Dy을 판다스에서 인식할 수 있는 datetime64타입으로 변경하라

In [67]:
df["Yr_Mo_Dy"] = pd.to_datetime(df["Yr_Mo_Dy"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   datetime64[ns]
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 667.8 KB

##### 66. Yr_Mo_Dy에 존재하는 년도의 유일값을 모두 출력하라

In [68]:
df["Yr_Mo_Dy"].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)

##### 67. Yr_Mo_Dy에 년도가 2061년 이상의 경우에는 모두 잘못된 데이터이다. 해당경우의 값은 100을 빼서 새롭게 날짜를 Yr_Mo_Dy 컬럼에 정의하라

In [69]:
import datetime as dt

def yearCheck(x):
    if x.year >= 2061: year = x.year - 100
    else: year = x.year
    return pd.to_datetime(dt.date(year, x.month, x.day))

df['Yr_Mo_Dy'] = df['Yr_Mo_Dy'].apply(yearCheck)
df.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

##### 68. 년도별 각컬럼의 평균값을 구하여라

In [70]:
df.groupby(df["Yr_Mo_Dy"].dt.year, as_index = False).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-07-02 00:00:00,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1,1962-07-02 00:00:00,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
2,1963-07-02 00:00:00,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
3,1964-07-01 12:00:00,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
4,1965-07-02 00:00:00,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
5,1966-07-02 00:00:00,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
6,1967-07-02 00:00:00,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
7,1968-07-01 12:00:00,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
8,1969-07-02 00:00:00,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
9,1970-07-02 00:00:00,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
10,1971-07-02 00:00:00,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
11,1972-07-01 12:00:00,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
12,1973-07-02 00:00:00,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
13,1974-07-02 00:00:00,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
14,1975-07-02 00:00:00,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
15,1976-07-01 12:00:00,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
16,1977-07-02 00:00:00,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
17,1978-07-02 00:00:00,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

##### 69. weekday컬럼을 만들고 요일별로 매핑하라 ( 월요일: 0 ~ 일요일 :6)

In [71]:
df["weekday"] = df["Yr_Mo_Dy"].dt.weekday
df

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,6
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,0
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,2
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,3
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,4
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,5
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,6

##### 70. weekday컬럼을 기준으로 주말이면 1 평일이면 0의 값을 가지는 WeekCheck 컬럼을 만들어라

In [72]:
df["WeekCheck"] = df["weekday"].apply(lambda x : 1 if 0 <= x <= 4 else 0)
df

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,6,0
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,0,1
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1,1
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2,1
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,2,1
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,3,1
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,4,1
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,5,0
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,6,0

##### 71. 년도, 일자 상관없이 모든 컬럼의 각 달의 평균을 구하여라

In [73]:
df["Month"] = df["Yr_Mo_Dy"].dt.month
target = df.drop("Yr_Mo_Dy", axis = 1)
target.groupby("Month", as_index = False).mean()

,Month,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
0,1,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763,2.989247,0.715054
1,2,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142,3.005906,0.712598
2,3,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317,3.000000,0.716846
3,4,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611,3.011111,0.711111
4,5,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039,2.982079,0.716846
5,6,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818,3.007407,0.714815
6,7,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789,3.001792,0.711470
7,8,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943,2.991039,0.716846
8,9,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963,3.009259,0.712963
9,10,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151,2.998208,0.713262
10,11,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185,2.992593,0.716667
11,12,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599,3.017921,0.711470

##### 72. ❌ 모든 결측치는 컬럼 기준 직전의 값으로 대체하고 첫번째 행에 결측치가 있을 경우 다음 행의 값으로 대체하라

In [74]:
df.fillna(method="ffill").fillna(method="bfill")

C:\Users\cho03\AppData\Local\Temp\ipykernel_4876\1073012706.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill").fillna(method="bfill")

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck,Month
0,1961-01-01,15.04,14.96,13.17,9.29,12.62,9.87,13.67,10.25,10.83,12.58,18.50,15.04,6,0,1
1,1961-01-02,14.71,14.96,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,0,1,1
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,10.04,8.50,7.67,12.75,12.71,1,1,1
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2,1,1
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,2,1,12
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,3,1,12
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,4,1,12
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,5,0,12
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,6,0,12

##### 73. 년도 - 월을 기준으로 모든 컬럼의 평균값을 구하여라

In [75]:
df.groupby([df["Yr_Mo_Dy"].dt.year, df["Yr_Mo_Dy"].dt.month], as_index = False).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck,Month
0,1961-01-16 00:00:00,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226,2.935484,0.709677,1.0
1,1961-02-14 12:00:00,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786,3.000000,0.714286,2.0
2,1961-03-16 00:00:00,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000,3.000000,0.741935,3.0
3,1961-04-15 12:00:00,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333,3.166667,0.666667,4.0
4,1961-05-16 00:00:00,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613,2.806452,0.741935,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,1978-08-16 00:00:00,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194,2.903226,0.741935,8.0
212,1978-09-15 12:00:00,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333,3.100000,0.700000,9.0
213,1978-10-16 00:00:00,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000,2.935484,0.709677,10.0
214,1978-11-15 12:00:00,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000,2.966667,0.733333,11.0
215,1978-12-16 00:00:00,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613,3.193548,0.677419,12.0

##### 74. ❌ RPT 컬럼의 값을 일자별 기준으로 1차 차분하라

In [76]:
df["RPT"].diff(periods = 1)

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ...
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

##### 75. ❌ RPT와 VAL의 컬럼을 일주일 간격으로 각각 이동 평균한 값을 구하여라

In [77]:
df[["RPT", "VAL"]].rolling(7).mean()

            RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

##### 76. ❌ 년-월-일:시 컬럼을 pandas에서 인식할 수 있는 datetime 형태로 변경하라. 서울시의 제공데이터의 경우 0시가 24시로 표현된다
서울시 미세먼지 데이터 : https://www.airkorea.or.kr/web/realSearch?pMENU_NO=97  
DataUrl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv’

In [78]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv")

In [79]:
import datetime as dt

def change(x):
    date = x.split(":")[0]
    hour = x.split(":")[1]

    if hour == "24":
        hour = "00:00:00"
        return pd.to_datetime(date + " " + hour) + dt.timedelta(days = 1)
    else:
        hour = hour + ":00:00"
        return pd.to_datetime(date + " " + hour)
    
df["(년-월-일:시)"] = df["(년-월-일:시)"].apply(change)
df.head()

,(년-월-일:시),PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스
0,2021-05-15 15:00:00,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003
1,2021-05-15 14:00:00,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003
2,2021-05-15 13:00:00,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004
3,2021-05-15 12:00:00,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004
4,2021-05-15 11:00:00,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005

##### 77. 일자별 영어 요일 이름을 dayName 컬럼에 저장하라

In [80]:
df["dayName"] = df["(년-월-일:시)"].dt.day_name()
df

,(년-월-일:시),PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스,dayName
0,2021-05-15 15:00:00,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003,Saturday
1,2021-05-15 14:00:00,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003,Saturday
2,2021-05-15 13:00:00,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004,Saturday
3,2021-05-15 12:00:00,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004,Saturday
4,2021-05-15 11:00:00,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,2021-03-25 05:00:00,보통,39.0,보통,18.0,좋음,0.026,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
1235,2021-03-25 04:00:00,보통,34.0,좋음,15.0,좋음,0.017,보통,0.033,좋음,0.4,좋음,0.002,Thursday
1236,2021-03-25 03:00:00,보통,35.0,좋음,13.0,좋음,0.029,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
1237,2021-03-25 02:00:00,보통,35.0,좋음,13.0,보통,0.031,좋음,0.025,좋음,0.3,좋음,0.003,Thursday
1238,2021-03-25 01:00:00,보통,42.0,좋음,13.0,좋음,0.022,보통,0.037,좋음,0.4,좋음,0.003,Thursday

##### 78. 일자별 각 PM10등급의 빈도수를 파악하라

In [81]:
ans = df.groupby(["dayName", "PM10등급"],as_index=False).size()
ans.pivot_table(index = "dayName", columns = "PM10등급", values = "size")

PM10등급       나쁨  매우나쁨     보통    좋음
dayName
Friday     31.0  17.0  120.0  21.0
Monday      1.0  21.0   83.0  63.0
Saturday   31.0  27.0   71.0  54.0
Sunday      2.0   1.0   67.0  98.0
Thursday   41.0   NaN  144.0   5.0
Tuesday    13.0  10.0   71.0  74.0
Wednesday  26.0   NaN   95.0  46.0

##### 79. ❌ 시간이 연속적으로 존재하며 결측치가 없는지 확인하라

In [82]:
check = len(df['(년-월-일:시)'].diff().unique())
if check == 2: print("True")
else: print("False")

True

##### 80. 오전 10시와 오후 10시(22시)의 PM10의 평균값을 각각 구하여라

In [83]:
print(df[df["(년-월-일:시)"].dt.hour == 10]["PM10"].mean())
print(df[df["(년-월-일:시)"].dt.hour == 22]["PM10"].mean())

70.38461538461539
69.94117647058823

##### 81. 날짜 컬럼을 index로 만들어라

In [84]:
df.set_index(["(년-월-일:시)"])

,PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스,dayName
(년-월-일:시),,,,,,,,,,,,,
2021-05-15 15:00:00,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003,Saturday
2021-05-15 14:00:00,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003,Saturday
2021-05-15 13:00:00,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004,Saturday
2021-05-15 12:00:00,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004,Saturday
2021-05-15 11:00:00,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-25 05:00:00,보통,39.0,보통,18.0,좋음,0.026,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
2021-03-25 04:00:00,보통,34.0,좋음,15.0,좋음,0.017,보통,0.033,좋음,0.4,좋음,0.002,Thursday
2021-03-25 03:00:00,보통,35.0,좋음,13.0,좋음,0.029,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
2021-03-25 02:00:00,보통,35.0,좋음,13.0,보통,0.031,좋음,0.025,좋음,0.3,좋음,0.003,Thursday
2021-03-25 01:00:00,보통,42.0,좋음,13.0,좋음,0.022,보통,0.037,좋음,0.4,좋음,0.003,Thursday

##### 82. ❌ 데이터를 주 단위로 뽑아서 최소,최대 평균, 표준표차를 구하여라

In [85]:
# 인덱스 설정
target = df.set_index("(년-월-일:시)")

# 주 단위 통계량
target.select_dtypes(exclude = object).resample("W").agg(["min", "max", "mean", "std"])

            PM10                                 PM2.5                    \
             min     max        mean         std   min    max       mean
(년-월-일:시)
2021-03-28   6.0   160.0   72.747368   43.345462   4.0  113.0  44.705263
2021-04-04   3.0   598.0   97.148810  129.911976   1.0  120.0  23.168675
2021-04-11  17.0   102.0   41.059524   16.325911   7.0   70.0  21.761905
2021-04-18   3.0   367.0   48.180723   43.254468   2.0   38.0  17.066265
2021-04-25  17.0   126.0   55.119048   26.659936   7.0   61.0  26.392857
2021-05-02   3.0    97.0   40.612121   24.813103   1.0   43.0  16.644578
2021-05-09   8.0  1024.0  161.660714  239.679148   3.0  172.0  34.738095
2021-05-16  16.0   111.0   40.014815   21.876855   7.0   76.0  21.577778

                          오존         ...     이산화질소           일산화탄소       \
                  std    min    max  ...      mean       std   min  max
(년-월-일:시)                            ...
2021-03-28  29.551928  0.002  0.085  ...  0.044579  0.023722   0.3  1.4
2021-04-04  22.399578  0.003  0.055  ...  0.027929  0.014978   0.3  0.9
2021-04-11  11.479343  0.009  0.070  ...  0.022583  0.009562   0.3  0.7
2021-04-18   7.867952  0.002  0.070  ...  0.023753  0.013553   0.3  0.6
2021-04-25  13.094788  0.006  0.090  ...  0.028571  0.014640   0.3  0.8
2021-05-02   8.850965  0.003  0.064  ...  0.020428  0.011676   0.3  0.6
2021-05-09  39.788248  0.002  0.073  ...  0.024187  0.012371   0.3  1.0
2021-05-16  15.622633  0.004  0.123  ...  0.030793  0.009503   0.3  0.8

                                아황산가스
                mean       std    min    max      mean       std
(년-월-일:시)
2021-03-28  0.611579  0.232408  0.002  0.006  0.003274  0.000961
2021-04-04  0.445833  0.135741  0.002  0.004  0.002732  0.000541
2021-04-11  0.389286  0.087573  0.002  0.004  0.002744  0.000569
2021-04-18  0.386747  0.084954  0.002  0.004  0.002464  0.000579
2021-04-25  0.457143  0.122142  0.001  0.011  0.003631  0.001763
2021-05-02  0.392771  0.092485  0.001  0.006  0.002524  0.000768
2021-05-09  0.419277  0.103230  0.002  0.004  0.002771  0.000579
2021-05-16  0.440741  0.094075  0.001  0.006  0.002459  0.001696

[8 rows x 24 columns]

# 6. Pivot
국가별 5세이하 사망비율 통계 : https://www.kaggle.com/utkarshxy/who-worldhealth-statistics-2020-complete  
Dataurl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv’

In [86]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv")

##### 83. Indicator을 삭제하고 First Tooltip 컬럼에서 신뢰구간에 해당하는 표현을 지워라

In [87]:
target = df.drop("Indicator", axis = 1)
target["First Tooltip"] = target["First Tooltip"].map(lambda x : x.split()[0])
target

          Location  Period        Dim1 First Tooltip
0      Afghanistan    2019  Both sexes         60.27
1      Afghanistan    2019        Male         63.83
2      Afghanistan    2019      Female         56.57
3      Afghanistan    2018  Both sexes         62.54
4      Afghanistan    2018        Male         66.08
...            ...     ...         ...           ...
29994  Timor-Leste    2002  Both sexes         96.97
29995  Timor-Leste    2002        Male         102.6
29996  Timor-Leste    2002      Female         91.04
29997  Timor-Leste    2001  Both sexes         102.5
29998  Timor-Leste    2001        Male         108.2

[29999 rows x 4 columns]

##### 84. 년도가 2015년 이상, Dim1이 Both sexes인 케이스만 추출하라

In [88]:
ans = target[(target["Period"] >= 2015) & (df["Dim1"] == "Both sexes")]
ans

          Location  Period        Dim1 First Tooltip
0      Afghanistan    2019  Both sexes         60.27
3      Afghanistan    2018  Both sexes         62.54
6      Afghanistan    2017  Both sexes         64.94
9      Afghanistan    2016  Both sexes         67.57
12     Afghanistan    2015  Both sexes         70.44
...            ...     ...         ...           ...
29943  Timor-Leste    2019  Both sexes         44.22
29946  Timor-Leste    2018  Both sexes         45.62
29949  Timor-Leste    2017  Both sexes         47.27
29952  Timor-Leste    2016  Both sexes         49.01
29955  Timor-Leste    2015  Both sexes         50.76

[860 rows x 4 columns]

##### 85. 84번 문제에서 추출한 데이터로 아래와 같이 나라에 따른 년도별 사망률을 데이터 프레임화 하라

In [89]:
ans.pivot(index = "Location", columns = "Period", values = "First Tooltip")

Period                                      2015   2016   2017   2018   2019
Location
Afghanistan                                70.44  67.57  64.94  62.54  60.27
Albania                                     9.57   9.42   9.42   9.53   9.68
Algeria                                    25.18  24.79  24.32  23.81  23.26
Andorra                                     3.53   3.37   3.22   3.09   2.97
Angola                                      88.2  84.21  80.62  77.67  74.69
...                                          ...    ...    ...    ...    ...
Syrian Arab Republic                       23.18  23.27  22.97  22.11  21.53
Tajikistan                                 37.75  36.82  35.81   34.8  33.78
Thailand                                    10.8  10.32   9.86   9.42   9.01
The former Yugoslav Republic of Macedonia  12.97  11.97   9.94   7.83   6.12
Timor-Leste                                50.76  49.01  47.27  45.62  44.22

[172 rows x 5 columns]

##### 86. Dim1에 따른 년도별 사망 비율의 평균을 구하라

In [100]:
target["First Tooltip"] = pd.to_numeric(target["First Tooltip"])
ans2 = target.groupby(["Dim1", "Period"])["First Tooltip"].mean().reset_index(name = "ratio")
ans2.pivot_table(index = "Dim1", columns = "Period", values = "ratio")

Period,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Dim1,,,,,,,,,,,,,,,,,,,,,
Both sexes,147.700816,155.537544,157.811094,156.147206,154.539857,155.797179,159.241163,156.170114,150.813222,150.574000,...,37.718488,35.573663,34.290988,33.099360,32.053314,31.012093,29.956337,29.030465,28.083837,27.191744
Female,140.909796,149.210175,151.516094,150.250882,148.688286,149.843205,153.048721,149.988295,144.719667,144.451474,...,34.953023,32.877616,31.654070,30.521337,29.524302,28.544360,27.542035,26.675291,25.782616,24.945349
Male,154.151224,161.538246,163.760781,161.742059,160.081000,161.456923,165.089535,162.015000,156.573556,156.375053,...,40.340174,38.140291,36.793081,35.543663,34.446105,33.354302,32.242616,31.273198,30.283023,29.350349

##### 87. 데이터에서 한국 KOR 데이터만 추출하라
올림픽 메달리스트 정보 데이터: https://www.kaggle.com/the-guardian/olympic-games  
dataUrl =’https://raw.githubusercontent.com/Datamanim/pandas/main/winter.csv’

In [102]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/winter.csv")
target = df[df["Country"] == "KOR"]
target

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
2652,1992,Albertville,Skating,Short Track Speed Skating,"LEE, Jun-Ho",KOR,Men,1000M,Bronze
2653,1992,Albertville,Skating,Short Track Speed Skating,"KIM, Ki-Hoon",KOR,Men,1000M,Gold
2671,1992,Albertville,Skating,Short Track Speed Skating,"KIM, Ki-Hoon",KOR,Men,5000M Relay,Gold
2672,1992,Albertville,Skating,Short Track Speed Skating,"LEE, Jun-Ho",KOR,Men,5000M Relay,Gold
2673,1992,Albertville,Skating,Short Track Speed Skating,"MO, Ji-Soo",KOR,Men,5000M Relay,Gold
...,...,...,...,...,...,...,...,...,...
5528,2014,Sochi,Skating,Short Track Speed Skating,"PARK, Seung-Hi",KOR,Women,500M,Bronze
5544,2014,Sochi,Skating,Speed skating,"JOO, Hyong Jun",KOR,Men,Team Pursuit,Silver
5545,2014,Sochi,Skating,Speed skating,"KIM, Cheol Min",KOR,Men,Team Pursuit,Silver
5546,2014,Sochi,Skating,Speed skating,"LEE, Seung Hoon",KOR,Men,Team Pursuit,Silver
5565,2014,Sochi,Skating,Speed skating,"LEE, Sang Hwa",KOR,Women,500M,Gold

##### 88. 한국 올림픽 메달리스트 데이터에서 년도에 따른 medal 갯수를 데이터프레임화 하라

In [ ]:
ans = target.groupby(["Year", "Medal"]).size().reset_index(name = "count")
ans.pivot_table(index = "Year", columns = "Medal", values = "count")

Medal  Bronze  Gold  Silver
Year
1992      1.0   5.0     1.0
1994      1.0   8.0     1.0
1998      2.0   6.0     4.0
2002      NaN   5.0     2.0
2006      2.0  14.0     3.0
2010      2.0   6.0    10.0
2014      2.0   7.0     5.0

##### 89. 전체 데이터에서 sport종류에 따른 성별수를 구하여라

In [107]:
ans = df.groupby(["Sport", "Gender"]).size().reset_index(name = "count")
ans.pivot_table(index = "Sport", columns = "Gender", values = "count")

Gender         Men  Women
Sport
Biathlon     270.0  150.0
Bobsleigh    416.0   36.0
Curling       97.0   75.0
Ice Hockey  1231.0  305.0
Luge         135.0   45.0
Skating      665.0  564.0
Skiing      1130.0  651.0

##### 90. 전체 데이터에서 Discipline종류에 따른 따른 Medal수를 구하여라

In [108]:
ans = df.groupby(["Discipline", "Medal"]).size().reset_index(name = "count")
ans.pivot_table(index = "Discipline", columns = "Medal", values = "count")

Medal                      Bronze   Gold  Silver
Discipline
Alpine Skiing               141.0  143.0   144.0
Biathlon                    139.0  140.0   141.0
Bobsleigh                   147.0  134.0   141.0
Cross Country Skiing        263.0  264.0   262.0
Curling                      56.0   58.0    58.0
Figure skating              118.0  122.0   119.0
Freestyle Skiing             34.0   34.0    34.0
Ice Hockey                  512.0  510.0   514.0
Luge                         60.0   62.0    58.0
Nordic Combined              55.0   55.0    55.0
Short Track Speed Skating    96.0   97.0    97.0
Skeleton                     10.0   10.0    10.0
Ski Jumping                  68.0   69.0    70.0
Snowboard                    30.0   30.0    30.0
Speed skating               190.0  193.0   197.0

# 7. Merge, Concat
국가별 5세이하 사망비율 통계 : https://www.kaggle.com/utkarshxy/who-worldhealth-statistics-2020-complete  
Dataurl = ‘https://raw.githubusercontent.com/Datamanim/pandas/main/mergeTEst.csv’

In [136]:
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/mergeTEst.csv", index_col = "Location")
df.head()

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.49,3.330,3.187,3.060,2.933,2.827
Angola,75.713,71.280,67.233,63.570,60.43,57.757,55.510,53.460,51.757,50.093

In [137]:
df1 = df.iloc[:4,:]
df2 = df.iloc[4:,:]

display(df1)
display(df2)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.49,3.330,3.187,3.060,2.933,2.827

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Angola,75.713,71.280,67.233,63.570,60.430,57.757,55.510,53.460,51.757,50.093
Antigua and Barbuda,8.667,8.223,7.807,7.420,7.070,6.757,6.483,6.230,6.000,5.783
Argentina,12.887,12.380,11.840,11.283,10.733,10.203,9.683,9.177,8.680,8.227
Armenia,16.497,15.677,14.897,14.170,13.477,12.817,12.183,11.583,11.007,10.497
Australia,3.993,3.803,3.623,3.467,3.343,3.253,3.183,3.137,3.090,3.047
Austria,3.573,3.463,3.333,3.210,3.113,3.043,2.987,2.943,2.897,2.843

#####

##### 91. df1과 df2 데이터를 하나의 데이터 프레임으로 합쳐라

In [138]:
ans = pd.concat([df1, df2])
ans.head()

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.49,3.330,3.187,3.060,2.933,2.827
Angola,75.713,71.280,67.233,63.570,60.43,57.757,55.510,53.460,51.757,50.093

##### 92. df3과 df4 데이터를 하나의 데이터 프레임으로 합쳐라. 둘다 포함하고 있는 년도에 대해서만 고려한다

In [139]:
df3 = df.iloc[:2,:4]
df4 = df.iloc[5:,3:]

display(df3)
display(df4)

               2010    2011    2012    2013
Location
Afghanistan  64.023  61.640  59.367  57.170
Albania      11.803  10.807   9.943   9.267

                       2013    2014    2015    2016    2017    2018    2019
Location
Antigua and Barbuda   7.420   7.070   6.757   6.483   6.230   6.000   5.783
Argentina            11.283  10.733  10.203   9.683   9.177   8.680   8.227
Armenia              14.170  13.477  12.817  12.183  11.583  11.007  10.497
Australia             3.467   3.343   3.253   3.183   3.137   3.090   3.047
Austria               3.210   3.113   3.043   2.987   2.943   2.897   2.843

In [140]:
ans = pd.concat([df3, df4], join = "inner")
ans

                       2013
Location
Afghanistan          57.170
Albania               9.267
Antigua and Barbuda   7.420
Argentina            11.283
Armenia              14.170
Australia             3.467
Austria               3.210

##### 93. df3과 df4 데이터를 하나의 데이터 프레임으로 합쳐라. 모든 컬럼을 포함하고, 결측치는 0으로 대체한다

In [141]:
ans = pd.concat([df3, df4], join = "outer").fillna(0)
ans

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,0.000,0.000,0.000,0.000,0.000,0.000
Albania,11.803,10.807,9.943,9.267,0.000,0.000,0.000,0.000,0.000,0.000
Antigua and Barbuda,0.000,0.000,0.000,7.420,7.070,6.757,6.483,6.230,6.000,5.783
Argentina,0.000,0.000,0.000,11.283,10.733,10.203,9.683,9.177,8.680,8.227
Armenia,0.000,0.000,0.000,14.170,13.477,12.817,12.183,11.583,11.007,10.497
Australia,0.000,0.000,0.000,3.467,3.343,3.253,3.183,3.137,3.090,3.047
Austria,0.000,0.000,0.000,3.210,3.113,3.043,2.987,2.943,2.897,2.843

##### 94. df5과 df6 데이터를 하나의 데이터 프레임으로 merge함수를 이용하여 합쳐라. Algeria컬럼을 key로 하고 두 데이터 모두 포함하는 데이터만 출력하라

In [142]:
df5 = df.T.iloc[:7,:3]
df6 = df.T.iloc[6:,2:5]

display(df5)
display(df6)

Location  Afghanistan  Albania  Algeria
2010           64.023   11.803   23.540
2011           61.640   10.807   22.907
2012           59.367    9.943   22.450
2013           57.170    9.267   22.117
2014           55.080    8.790   21.850
2015           53.107    8.493   21.587
2016           51.267    8.363   21.257

Location  Algeria  Andorra  Angola
2016       21.257    3.187  55.510
2017       20.850    3.060  53.460
2018       20.407    2.933  51.757
2019       19.930    2.827  50.093

In [143]:
pd.merge(df5, df6, on = "Algeria", how = "inner")

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0              51.267    8.363   21.257    3.187   55.51

##### 95. df5과 df6 데이터를 하나의 데이터 프레임으로 merge함수를 이용하여 합쳐라. Algeria컬럼을 key로 하고 합집합으로 합쳐라

In [144]:
pd.merge(df5, df6, on = "Algeria", how = "outer")

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0                 NaN      NaN   19.930    2.827  50.093
1                 NaN      NaN   20.407    2.933  51.757
2                 NaN      NaN   20.850    3.060  53.460
3              51.267    8.363   21.257    3.187  55.510
4              53.107    8.493   21.587      NaN     NaN
5              55.080    8.790   21.850      NaN     NaN
6              57.170    9.267   22.117      NaN     NaN
7              59.367    9.943   22.450      NaN     NaN
8              61.640   10.807   22.907      NaN     NaN
9              64.023   11.803   23.540      NaN     NaN